org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.2
fabric_loader_version=0.19.1
fabric_api_version=0.158.0+26.2

## CurseForge dependency file IDs
# Trade Cycling 1.0.21+26.2 Fabric
trade_cycling_file_id=8271477

## Mod Properties

mod_id=librarian_trade_cycler
mod_loader=fabric
mod_name=Villager Trade Finder
mod_license=MIT
mod_version=1.7.0
mod_group_id=com.uncraftbar.easyautocycler
mod_authors=CNTrident
mod_description=Automatically cycles profession-villager trades until a configured enchanted-book or item target is found.
