org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1.2
fabric_loader_version=0.19.1
fabric_api_version=0.146.0+26.1.2
fabric_api_base_version=2.0.3+ece063234c
fabric_key_mapping_api_version=2.0.4+e2bdee784c
fabric_networking_api_version=6.3.0+50a808ce4c
fabric_resource_loader_version=3.3.16+4fc5413f4c
fabric_screen_api_version=5.0.1+d871b99e4c

## CurseForge dependency file IDs
# Trade Cycling 1.0.21+26.1.2 Fabric
trade_cycling_file_id=8020648

## Mod Properties

mod_id=librarian_trade_cycler
mod_loader=fabric
mod_name=Librarian Trade Cycler
mod_license=MIT
mod_version=1.1.0
mod_group_id=com.uncraftbar.easyautocycler
mod_authors=CNTrident
mod_description=Automatically cycles unlocked librarian trades until an exact enchanted-book and original-price target is found.
